// Unified product model and data for all products
export type Product = {
  id: number;
  slug: string;
  title: string;
  coverImage: string;
  images: string[];
  newPrice: number;
  oldPrice: number;
  quantityUnit: string;
  reviewStars: number;
  reviews: number;
  description: string;
  healthBenefits: string;
  variants?: string[];
  category: string;
  inStock: boolean;
  isNew: boolean;
  isSale: boolean;
  pros?: string[];
  cons?: string[];
};

export const PRODUCTS: Product[] = [
  {
    id: 1,
    slug: "buckwheat",
    title: "Buckwheat",
    coverImage: "/assets/quail.jpeg",
    images: ["/assets/quail.jpeg", "/assets/b1.jpg"],
    newPrice: 450,
    oldPrice: 500,
    quantityUnit: "1kg",
    reviewStars: 4.8,
    reviews: 120,
    description: "Pure Hunza buckwheat, rich in nutrients and flavor.",
    healthBenefits: "Supports heart health, gluten-free, high in fiber.",
    variants: ["1kg", "2kg"],
    category: "Hunza foods",
    inStock: true,
    isNew: true,
    isSale: false,
    pros: ["High in fiber", "Gluten-free"],
    cons: ["May be expensive"],
  },
  {
    id: 2,
    slug: "hunza-tea",
    title: "Hunza Tea",
    coverImage: "/assets/b1.jpg",
    images: ["/assets/b1.jpg", "/assets/b2.jpg"],
    newPrice: 350,
    oldPrice: 400,
    quantityUnit: "250g",
    reviewStars: 4.7,
    reviews: 80,
    description: "Traditional Hunza tea, aromatic and healthy.",
    healthBenefits: "Rich in antioxidants, boosts immunity.",
    variants: ["250g", "500g"],
    category: "Hunza foods",
    inStock: true,
    isNew: false,
    isSale: true,
    pros: ["Rich in antioxidants", "Boosts immunity"],
    cons: ["May be expensive"],
  },
  {
    id: 3,
    slug: "desi-ghee",
    title: "Desi Ghee",
    coverImage: "/assets/b2.jpg",
    images: ["/assets/b2.jpg", "/assets/b3.jpg"],
    newPrice: 1800,
    oldPrice: 2000,
    quantityUnit: "1L",
    reviewStars: 4.9,
    reviews: 150,
    description: "Pure desi ghee made from grass-fed cow milk.",
    healthBenefits: "Good for digestion, rich in healthy fats.",
    variants: ["500ml", "1L"],
    category: "Desi foods",
    inStock: true,
    isNew: false,
    isSale: true,
    pros: ["Good for digestion", "Rich in healthy fats"],
    cons: ["May be expensive"],
  },
  {
    id: 4,
    slug: "chia-seeds",
    title: "Chia Seeds",
    coverImage: "/assets/b3.jpg",
    images: ["/assets/b3.jpg", "/assets/1.jpg"],
    newPrice: 600,
    oldPrice: 700,
    quantityUnit: "500g",
    reviewStars: 4.9,
    reviews: 110,
    description: "Organic chia seeds, perfect for smoothies and baking.",
    healthBenefits: "High in omega-3, fiber, and protein.",
    variants: ["250g", "500g"],
    category: "Tibbi foods",
    inStock: true,
    isNew: true,
    isSale: false,
    pros: ["High in omega-3", "Fiber", "Protein"],
    cons: ["May be expensive"],
  },
  {
    id: 5,
    slug: "basmati-rice",
    title: "Basmati Rice",
    coverImage: "/assets/1.jpg",
    images: ["/assets/1.jpg", "/assets/b1.jpg"],
    newPrice: 120,
    oldPrice: 150,
    quantityUnit: "1kg",
    reviewStars: 4.5,
    reviews: 120,
    description: "Premium long-grain basmati rice.",
    healthBenefits: "Low glycemic index, easy to digest.",
    variants: ["1kg", "5kg"],
    category: "General grocery",
    inStock: true,
    isNew: false,
    isSale: false,
    pros: ["Low glycemic index", "Easy to digest"],
    cons: ["May be expensive"],
  },
  {
    id: 6,
    slug: "olive-oil",
    title: "Olive Oil",
    coverImage: "/assets/b1.jpg",
    images: ["/assets/b1.jpg", "/assets/b2.jpg"],
    newPrice: 1200,
    oldPrice: 1400,
    quantityUnit: "500ml",
    reviewStars: 4.7,
    reviews: 80,
    description: "Cold-pressed extra virgin olive oil.",
    healthBenefits: "Heart healthy, rich in antioxidants.",
    variants: ["250ml", "500ml"],
    category: "Tibbi foods",
    inStock: true,
    isNew: false,
    isSale: false,
    pros: ["Heart healthy", "Rich in antioxidants"],
    cons: ["May be expensive"],
  },
  {
    id: 7,
    slug: "quinoa-organic",
    title: "Quinoa Organic",
    coverImage: "/assets/b2.jpg",
    images: ["/assets/b2.jpg", "/assets/b3.jpg"],
    newPrice: 899,
    oldPrice: 999,
    quantityUnit: "500g",
    reviewStars: 4.6,
    reviews: 45,
    description: "Organic quinoa, a superfood for your meals.",
    healthBenefits: "Complete protein, gluten-free.",
    variants: ["250g", "500g"],
    category: "General grocery",
    inStock: true,
    isNew: true,
    isSale: false,
    pros: ["Complete protein", "Gluten-free"],
    cons: ["May be expensive"],
  },
  {
    id: 8,
    slug: "wildflower-honey",
    title: "Wildflower Honey",
    coverImage: "/assets/b3.jpg",
    images: ["/assets/b3.jpg", "/assets/1.jpg"],
    newPrice: 399,
    oldPrice: 499,
    quantityUnit: "500g",
    reviewStars: 4.6,
    reviews: 34,
    description: "Raw wildflower honey, unfiltered and pure.",
    healthBenefits: "Natural energy, soothes sore throat.",
    variants: ["250g", "500g"],
    category: "Hunza foods",
    inStock: true,
    isNew: false,
    isSale: true,
    pros: ["Natural energy", "Soothes sore throat"],
    cons: ["May be expensive"],
  },
]; 